name: Update Curves

on:
  schedule:
    # Daily at 22:30 UTC
    - cron: '30 22 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy matplotlib requests pandas_datareader

      - name: Regenerate curves and figures
        run: |
          python "Yield Curve PCA.py"
      
      - name: Update README to latest dated image
        run: |
          latest=$(ls -1 reports/figures/curves_*.png | sort | tail -n1)
          base=$(basename "$latest")
          sed -i -E "s|reports/figures/(curves_latest|curves_[0-9]{4}-[0-9]{2}-[0-9]{2}).png|reports/figures/${base}|g" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/treasury_yields.csv reports/figures/*.png README.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update curves [skip ci]"
            git push
          fi
